const env = import.meta.env;

export const SUPABASE_URL = env.VITE_SUPABASE_URL || env.REACT_APP_SUPABASE_URL;
export const SUPABASE_KEY =
  env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  env.REACT_APP_SUPABASE_PUBLISHABLE_KEY ||
  env.VITE_SUPABASE_ANON_KEY ||
  env.REACT_APP_SUPABASE_ANON_KEY;
export const DASHBOARD_ADMIN_EMAILS =
  env.VITE_DASHBOARD_ADMIN_EMAILS || env.REACT_APP_DASHBOARD_ADMIN_EMAILS || '';

export const CLOUDINARY_CLOUD_NAME =
  env.VITE_CLOUDINARY_CLOUD_NAME || env.REACT_APP_CLOUDINARY_CLOUD_NAME;
export const CLOUDINARY_UPLOAD_PRESET =
  env.VITE_CLOUDINARY_UPLOAD_PRESET || env.REACT_APP_CLOUDINARY_UPLOAD_PRESET;
export const CLOUDINARY_API_KEY =
  env.VITE_CLOUDINARY_API_KEY || env.REACT_APP_CLOUDINARY_API_KEY;

export const WHATSAPP_NUMBER =
  env.VITE_WHATSAPP_NUMBER || env.REACT_APP_WHATSAPP_NUMBER || '963965578857';
export const AI_HORDE_KEY = env.VITE_AI_HORDE_KEY || env.REACT_APP_AI_HORDE_KEY;
