export const INIT_CATS = [
  { id: "all", image: "/romantic.png", icon: "💐", grad: "linear-gradient(135deg,#3a2a1a,#1c1510)" },
  { id: "romantic", image: "/romantic.png", icon: "🌹", grad: "linear-gradient(135deg,#5c1a2a,#2a0a10)" },
  { id: "graduation", image: "/graduation.png", icon: "🎓", grad: "linear-gradient(135deg,#3a2e0a,#1a1408)" },
  { id: "getWell", image: "/getwell.png", icon: "🌸", grad: "linear-gradient(135deg,#2a1a2e,#120a18)" },
  { id: "birthday", image: "/birthday.png", icon: "🎂", grad: "linear-gradient(135deg,#1a1a3a,#0a0a1c)" },
  { id: "wedding", image: "/wedding.png", icon: "💍", grad: "linear-gradient(135deg,#1a1a1a,#0d0d0d)" },
  { id: "sympathy", image: "/sympathy.png", icon: "🕊️", grad: "linear-gradient(135deg,#0a1a1a,#050e0e)" },
];

export const INIT_PRODUCTS = [
  {
    id: 1,
    name: { en: "Eternal Red Roses", ar: "ورد أحمر أبدي" },
    nameAr: "ورد أحمر أبدي",
    category: "romantic",
    type: "bouquet",
    colors: ["red"],
    occasion: ["love", "apology"],
    budgetTier: "medium",
    size: "24 flowers",
    wrappingStyle: "Black wrap with gold ribbon",
    price: 65000,
    image: "/1.jpeg",
    images: ["/1.jpeg"],
    icon: "🌹",
    count: 24,
    includes: ["Fresh seasonal red flowers", "Premium wrapping", "Optional message card"],
    description: {
      en: "Premium red roses in a dramatic dark wrap, prepared fresh for a confident romantic gesture.",
      ar: "ورود حمراء فاخرة بتغليف داكن أنيق، تُحضّر طازجة لهدية رومانسية واضحة.",
    },
  },
  {
    id: 2,
    name: { en: "Graduation Pride", ar: "فخر التخرج" },
    nameAr: "فخر التخرج",
    category: "graduation",
    type: "bouquet",
    colors: ["yellow", "white"],
    occasion: ["graduation", "congratulations"],
    budgetTier: "premium",
    size: "30 flowers",
    wrappingStyle: "Light premium wrap",
    price: 75000,
    image: "/graduation.png",
    images: ["/graduation.png"],
    icon: "🌻",
    count: 30,
    includes: ["Fresh seasonal flowers", "Premium wrapping", "Optional message card"],
    description: {
      en: "A bright yellow and white bouquet designed for graduations, achievements, and proud moments.",
      ar: "باقة صفراء وبيضاء مشرقة للتخرج والإنجازات ولحظات الفخر.",
    },
  },
  {
    id: 3,
    name: { en: "Healing Garden", ar: "حديقة الشفاء" },
    nameAr: "حديقة الشفاء",
    category: "getWell",
    type: "bouquet",
    colors: ["pink", "white"],
    occasion: ["congratulations"],
    budgetTier: "low",
    size: "15 flowers",
    wrappingStyle: "Soft natural wrap",
    price: 45000,
    image: "/getwell.png",
    images: ["/getwell.png"],
    icon: "🌷",
    count: 15,
    includes: ["Fresh seasonal flowers", "Premium wrapping", "Optional message card"],
    description: {
      en: "Soft pink and white flowers for gentle wishes, recovery, and warm daily surprises.",
      ar: "زهور وردية وبيضاء ناعمة للأمنيات اللطيفة والتعافي والمفاجآت الدافئة.",
    },
  },
  {
    id: 4,
    name: { en: "Birthday Bliss", ar: "سعادة عيد الميلاد" },
    nameAr: "سعادة عيد الميلاد",
    category: "birthday",
    type: "bouquet",
    colors: ["mixed", "pink"],
    occasion: ["birthday", "congratulations"],
    budgetTier: "medium",
    size: "20 flowers",
    wrappingStyle: "Festive premium wrap",
    price: 55000,
    image: "/birthday.png",
    images: ["/birthday.png"],
    icon: "🌸",
    count: 20,
    includes: ["Fresh seasonal flowers", "Premium wrapping", "Optional message card"],
    description: {
      en: "A joyful mixed bouquet with a festive color story for birthdays and happy celebrations.",
      ar: "باقة مبهجة بألوان مختلطة لعيد الميلاد والمناسبات السعيدة.",
    },
  },
  {
    id: 5,
    name: { en: "Bridal Grace", ar: "رونق العروس" },
    nameAr: "رونق العروس",
    category: "wedding",
    type: "bouquet",
    colors: ["white"],
    occasion: ["love", "congratulations"],
    budgetTier: "premium",
    size: "50 flowers",
    wrappingStyle: "Elegant white wrap",
    price: 120000,
    image: "/wedding.png",
    images: ["/wedding.png"],
    icon: "🤍",
    count: 50,
    includes: ["Fresh seasonal white flowers", "Premium wrapping", "Optional message card"],
    description: {
      en: "A graceful white bouquet for weddings, engagements, and elegant congratulations.",
      ar: "باقة بيضاء راقية للأعراس والخطوبة والتهنئة الأنيقة.",
    },
  },
  {
    id: 6,
    name: { en: "Peaceful Sympathy", ar: "تعازي هادئة" },
    nameAr: "تعازي هادئة",
    category: "sympathy",
    type: "bouquet",
    colors: ["white"],
    occasion: ["apology"],
    budgetTier: "medium",
    size: "18 flowers",
    wrappingStyle: "Simple cream wrap",
    price: 50000,
    image: "/sympathy.png",
    images: ["/sympathy.png"],
    icon: "🕊️",
    count: 18,
    includes: ["Fresh seasonal white flowers", "Premium wrapping", "Optional message card"],
    description: {
      en: "A quiet white and cream arrangement for gentle support, sympathy, and sincere apologies.",
      ar: "تنسيق هادئ بالأبيض والكريمي للدعم اللطيف والتعازي والاعتذار الصادق.",
    },
  },
  {
    id: 7,
    name: { en: "Pink Romance", ar: "الرومانسية الوردية" },
    nameAr: "الرومانسية الوردية",
    category: "romantic",
    type: "bouquet",
    colors: ["pink"],
    occasion: ["love", "birthday"],
    budgetTier: "medium",
    size: "20 flowers",
    wrappingStyle: "Blush wrap",
    price: 60000,
    image: "/2.jpeg",
    images: ["/2.jpeg"],
    icon: "🌺",
    count: 20,
    includes: ["Fresh seasonal pink flowers", "Premium wrapping", "Optional message card"],
    description: {
      en: "A soft pink bouquet with romantic texture and a gentle luxury finish.",
      ar: "باقة وردية ناعمة بطابع رومانسي ولمسة فاخرة هادئة.",
    },
  },
  {
    id: 8,
    name: { en: "Scholar's Triumph", ar: "انتصار العالم" },
    nameAr: "انتصار العالم",
    category: "graduation",
    type: "bouquet",
    colors: ["yellow", "white"],
    occasion: ["graduation", "congratulations"],
    budgetTier: "premium",
    size: "35 flowers",
    wrappingStyle: "Gold-accent wrap",
    price: 85000,
    image: "/3.jpeg",
    images: ["/3.jpeg"],
    icon: "🌼",
    count: 35,
    includes: ["Fresh seasonal flowers", "Premium wrapping", "Optional message card"],
    description: {
      en: "A fuller graduation bouquet in bright yellow and white with a celebratory finish.",
      ar: "باقة تخرج أكبر بالأصفر والأبيض مع لمسة احتفالية أنيقة.",
    },
  },
];
